# PcCheckTool settings
topmost=true
battery_green_health=40
battery_red_health=39
battery_green_capacity=0
battery_red_capacity=0
software_display_name=电脑检测工具
office_key_source=3.txt
office_key_target=D:\\Users\\Desktop\\【重要】プロダクトキー情報とお問い合わせ先.txt
office_key_operation=cut
office_low_key_warning=0
office_activation_count=0
office_comm_window_title=任务流窗口
office_comm_window_description=用于按顺序运行指定目录中的可执行程序，并展示每一步的执行结果与耗时。
office_comm_test_url=任务流示例_全成功
office_comm_test_payload=示例：默认会顺序执行 任务流示例 目录里的 10 个示例文件。<<NL>>你也可以改成自己的说明、批注或临时文本。
office_comm_step_delay=300
office_custom_action_text=发送按键串
office_custom_action_path=内置:发送按键串
office_custom_actions_text=打开右键示例\p自定义右键示例\\自定义右键说明.txt
office_custom_key_list_title=键入Office密钥
office_custom_file_list_title=自定义可执行文件/文档
office_custom_key_actions_text=发送按键串<<NL>>按键:{Alt}<<NL>>停顿:250<<NL>>按键:D<<NL>>停顿:400<<NL>>按键:Y<<NL>>停顿:200<<NL>>按键:4<<NL>>停顿:500<<NL>>按键:{Tab}<<NL>>停顿:250<<NL>>按键:{Tab}<<NL>>停顿:250<<NL>>按键:{Tab}<<NL>>停顿:500<<NL>>按键:^v<<NL>>停顿:500<<NL>>按键:{Tab}<<NL>>停顿:500<<NL>>按键:{Enter}
office_custom_file_actions_text=打开右键示例\p自定义右键示例\\自定义右键说明.txt
camera_check_path=
keyboard_check_path=Keyboard Test Utility.exe
speaker_test_path=资源文件\\【俺妹】俺の妹がこんなに可愛いわけがないop「irony」.mp4
icon_file_path=
windows_activation_copy_template=slmgr /ipk {key}
github_url=https://github.com/dashboard
donate_url=https://github.com/dashboard
software_updated_at=2026-03-22
theme_mode=dark
window_width=923
window_height=924
window_left=740
window_top=38
window_maximized=false
zen_window_left=350
zen_window_top=612
speedrun_window_left=98
speedrun_window_top=332
wifi=Redmi 12 5G|123456789|WPA2PSK|AES
