# PcCheckTool settings
topmost=true
battery_green_health=40
battery_red_health=39
battery_green_capacity=0
battery_red_capacity=0
software_display_name=电脑检测工具
office_key_source=3.txt
office_key_target=D:\\Users\\Desktop\\【重要】プロダクトキー情報とお問い合わせ先.txt
office_key_operation=copy
office_low_key_warning=0
office_activation_count=0
office_post_action_enabled=true
office_post_action_condition=键入office码
office_post_action_sequence=按键:{Alt}<<NL>>停顿:250<<NL>>按键:D<<NL>>停顿:400<<NL>>按键:Y<<NL>>停顿:200<<NL>>按键:4<<NL>>停顿:500<<NL>>按键:{Tab}<<NL>>停顿:250<<NL>>按键:{Tab}<<NL>>停顿:250<<NL>>按键:{Tab}<<NL>>停顿:500<<NL>>按键:^v<<NL>>停顿:500<<NL>>按键:{Tab}<<NL>>停顿:500<<NL>>按键:{Enter}
office_post_ahk_enabled=false
office_post_ahk_path=AutoHotkey.exe
office_post_ahk_script=
office_comm_test_url=http://10.229.159.132:8000
office_comm_test_payload=Office 通信测试<<NL>>只发送模拟文本，不包含激活数据。
camera_check_path=
keyboard_check_path=Keyboard Test Utility.exe
speaker_test_path=资源文件\\【俺妹】俺の妹がこんなに可愛いわけがないop「irony」.mp4
icon_file_path=
windows_activation_copy_template=slmgr /ipk {key}
github_url=https://github.com/dashboard
donate_url=https://github.com/dashboard
software_updated_at=2026-03-21
theme_mode=dark
window_width=940
window_height=924
window_left=964
window_top=101
window_maximized=false
zen_window_left=1189
zen_window_top=431
speedrun_window_left=1596
speedrun_window_top=316
wifi=Redmi 12 5G|123456789|WPA2PSK|AES
